### ISSUE TITLE
Demo code breaks in new Python2 version, 2.7.14, due to XMLRPC changes

### ISSUE THREAD

**Issue by awwad** [uptane/obsolete-reference-implementation#150]
## Bug Report
When running the demonstration code in Python 2.7.14 (released two months ago), the demonstration Secondary fails to parse the timeserver attestation provided it by the demonstration Primary.

The error is below.

```Python
Generating this Secondary's first ECU Version Manifest and sending it to the Primary.
>>> ds.update_cycle()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "demo/demo_secondary.py", line 291, in update_cycle
    time_attestation = pserver.get_last_timeserver_attestation()
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1316, in single_request
    return self.parse_response(response)
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1487, in parse_response
    p.feed(data)
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 558, in feed
    self._parser.Parse(data, 0)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 5, column 16
>>>
```

This occurs due to changes made to the `xmlrpc` library in Python 2.7.14. Changelog [here](https://raw.githubusercontent.com/python/cpython/84471935ed2f62b8c5758fd544c7d37076fe0fa5/Misc/NEWS).

Python 2.7.14 ships with Mac OS X High Sierra, among other systems.

A fix should be crafted that doesn't break compatibility with Python < 2.7.14 or Python3.

**Comment by awwad** [comment]
This was reported by @aramchandran.

**Comment by vladimir-v-diaz** [comment]
It might be more helpful to indicate the specific entry in the Python CHANGELOG that is backwards-incompatible.  One option is to quote the specific change here.  Another is to link to a specific line, if possible.

**Comment by awwad** [comment]
I had the same thought. I'm not sure which of several it was yet. I have a hypothesis, but it'll take some tinkering.

**Comment by abhi-hacks** [comment]
I found this resource https://stackoverflow.com/questions/11443036/xml-parsing-in-python-expaterror-not-well-formed
Will try this tonight.

**Comment by awwad** [comment]
PR #151 fixes this.
