### ISSUE TITLE
Not able to run server and primary on different systems

### ISSUE THREAD

**Issue by dcs2020** [uptane/obsolete-reference-implementation#200]
Hi, 
I am running Server on desktop and running  Primary on another system, for the setup in demo/_init.py  file I have modified LOCAL with ip address of server  and in demo/pinned_primary_template.json  file I am modifiying local host with IP address of server but primary is not able to connect to server i am getting error as below:

>>> import demo.demo_primary as dp
>>> dp.clean_slate()

Primary is now listening for messages from Secondaries.
Registering Primary ECU Serial and Key with Director.
Primary will now listen on port 30701
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/root/uptane/demo/demo_primary.py", line 155, in clean_slate
    register_self_with_director()
  File "/home/root/uptane/demo/demo_primary.py", line 385, in register_self_with_director
    _vin, True)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1092, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1432, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1134, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1146, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1259, in send_request
    self.send_content(connection, request_body)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1289, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 712, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

Please help me out to solve the issue.

Thank you,
Deepthi

**Comment by JustinCappos** [comment]
Are you actually able to connect between the systems yourself with netcat
or similar?  Do you have a host firewall on a system or anything else that
may block communication?

**Comment by dcs2020** [comment]
Hi Justin,

Thank you for the respone.

Are you actually able to connect between the systems yourself with netcat or similar?
Yes, I am able to ping from one system to another through ssh and ping commands but connection is not happening between server and primary.

Do you have a host firewall on a system or anything else that may block communication?
No, I dont have any firewall I am using open access network system.

Thank you,
Deepthi

**Comment by JustinCappos** [comment]
The Uptane repository is just a web server.  Can you connect to it that way
to test?

**Comment by dcs2020** [comment]
Hi Justin,

I tried to connect it through nc command but it is not able to connect.

Thank you,
Deepthi

**Comment by JustinCappos** [comment]
Okay, if you can't connect through nc, then it is a problem with your
network setup, not a problem with the Uptane code.  You likely have some
iptables rules, firewall rules, etc. in place that are blocking HTTP
traffic.

I'm not sure what to tell you except you'll need to fix this before being
able to get Uptane to run.  I'd recommend just getting a basic HTTP server
/ client setup working first and then running the Uptane code.
