### ISSUE TITLE
demo_timeserver.py exception

### ISSUE THREAD

**Issue by vladimir-v-diaz** [uptane/obsolete-reference-implementation#60]
I recently pulled in the latest changes from "develop".  It appears something was changed in create_signature() that is causing timeserver.py to fail.  The exception is provided below.

```Bash
$ python demo/demo_timeserver.py 
Loading timeserver signing key.
Timeserver signing key loaded.
Traceback (most recent call last):
  File "demo/demo_timeserver.py", line 168, in <module>
    listen()
  File "demo/demo_timeserver.py", line 89, in listen
    test_demo_timeserver()
  File "demo/demo_timeserver.py", line 140, in test_demo_timeserver
    der_signed_time = timeserver.get_signed_time_der([2, 9, 151])
  File "/home/vlad/projects/vladforks/tmp/uptane/uptane/services/timeserver.py", line 95, in get_signed_time_der
    resign=True)
  File "/home/vlad/projects/vladforks/tmp/uptane/uptane/encoding/asn1_codec.py", line 331, in convert_signed_metadata_to_der
    private_key, hash_of_der, force_non_json=True, is_binary_data=True)]
TypeError: create_signature() got an unexpected keyword argument 'force_non_json'
```

**Comment by awwad** [comment]
Develop branch demo timeserver works for me. The TUF fork has been updated. Update your TUF code. (:

(Is there some way I can help automate this for people? :P)

**Comment by awwad** [comment]
Confirm it's OK?

**Comment by vladimir-v-diaz** [comment]
I pulled from uptane/uptane and still get the error.  It must be in your fork of TUF.

```Bash
$ git pull git@github.com:uptane/uptane.git
From github.com:uptane/uptane
 * branch            HEAD       -> FETCH_HEAD
Auto-merging demo/demo_secondary.py
Auto-merging demo/demo_director.py
Merge made by the 'recursive' strategy.
 demo/demo_director.py                          |  25 ++++++++++-
 demo/demo_primary.py                           |  38 +++++++++++++---
 demo/demo_secondary.py                         |  16 +++++--
 tests/test_der_encoder.py                      | 213 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-
 tests/test_primary.py                          |  39 ++++++++++++-----
 uptane/clients/primary.py                      |  39 ++++++++++++++---
 uptane/clients/secondary.py                    |   9 ++++
 uptane/encoding/asn1_codec.py                  | 191 +++++++++++++++++++++++++++++++++++++++++++++++++++++++------------------------
 uptane/encoding/ecu_manifest_asn1_coder.py     |  42 ++++++++++++------
 uptane/encoding/vehicle_manifest_asn1_coder.py |  78 +++++++++++++++++++++++++++------
 uptane/formats.py                              |   4 ++
 uptane/services/director.py                    |  63 ++++++++++++++++++++++++---
 12 files changed, 637 insertions(+), 120 deletions(-)
(env)$ python demo/demo_timeserver.py 
Loading timeserver signing key.
Timeserver signing key loaded.
Traceback (most recent call last):
  File "demo/demo_timeserver.py", line 168, in <module>
    listen()
  File "demo/demo_timeserver.py", line 89, in listen
    test_demo_timeserver()
  File "demo/demo_timeserver.py", line 140, in test_demo_timeserver
    der_signed_time = timeserver.get_signed_time_der([2, 9, 151])
  File "/home/vlad/projects/vladforks/tmp/uptane/uptane/services/timeserver.py", line 95, in get_signed_time_der
    resign=True)
  File "/home/vlad/projects/vladforks/tmp/uptane/uptane/encoding/asn1_codec.py", line 351, in convert_signed_metadata_to_der
    private_key, hash_of_der, force_non_json=True, is_binary_data=True)]
TypeError: create_signature() got an unexpected keyword argument 'force_non_json'
```

**Comment by vladimir-v-diaz** [comment]
I just pulled from your fork of TUF and I got a bunch of merge conflicts.  Let me resolve them and get back to you.  Most of the conflicts are with tox.in and similar files.

**Comment by vladimir-v-diaz** [comment]
Pulling from your latest fork of TUF did the trick!
